.\" You can view this file with:
.\" man -l urler.1
.\" Written by Daniel Stenberg
.\"
.TH urler 1 "31 Mar 2023" "urler 0.1" "urler Manual"
.SH NAME
urler \- parse and manipulate URLs
.SH SYNOPSIS
.B urler [options]
.SH DESCRIPTION
.B urler
parses, manipulates and outputs URLs and parts of URLs.

It uses the RFC 3986 definition of URLs and it uses libcurl's URL parser to do
so, which includes a few "extensions".

Typically you set a few inputs and decide what of that you want output.
.SH "MISC OPTIONS"
.IP "-h, --help"
Show the help output.
.IP "-v, --version"
Show version information and exit.
.SH "INPUT OPTIONS"
.IP "--url [URL]"
Set the input URL to work with. The URL may be provided without a scheme,
which then typically is not actually a legal URL but urler will try to figure
out what is meant and guess what scheme to use.

Providing multiple URLs will make urler act on all URLs in a serial fashion.
.IP "--redirect [URL]"
Redirect the base URL to this. It requires that you set the base url with \fB--url\fP
.IP "--append-path [segment]"
URL encodes and appends this segment to the path, separated with a slash.
.IP "--append-query [segment]"
URL encodes and appends this segment to the query, separated with an ampersand
(&). If the segment contains an equal sign ('=') that will be kept verbatim
and both sides of the first occrance will be URL encoded separately.
.IP "--set-fragment [fragment]"
Set this fragment. Setting it to a blank string ("") will clear it from the
URL.
.IP "--set-host [host]"
Set this host name. Setting it to a blank string ("") will clear it from the
URL.
.IP "--set-options [options]"
Set these options. Setting it to a blank string ("") will clear it from the
URL.
.IP "--set-password [secret]"
Set this password. Setting it to a blank string ("") will clear it from the
URL.
.IP "--set-path [path]"
Set this path. Setting it to a blank string ("") will clear it from the URL.
.IP "--set-port [port]"
Set this port number. Setting it to a blank string ("") will clear it from the
URL.
.IP "--set-query [query]"
Set this query. Setting it to a blank string ("") will clear it from the URL.
.IP "--set-scheme [scheme]"
Set this scheme. Setting it to a blank string ("") will clear it from the URL.
.IP "--set-user [name]"
Set this user.
.IP "--set-zoneid [zoneid]"
Set this zone id.
.SH "OUTPUT OPTIONS"
.IP "--get-fragment"
Output only the fragment part.
.IP "--get-host"
Output only the host part.
.IP "--get-options"
Output only the options part.
.IP "--get-password"
Output only the password part.
.IP "--get-path"
Output only the path part.
.IP "--get-port"
Output only the port part.
.IP "--get-query"
Output only the query part.
.IP "--get-scheme"
Output only the scheme part.
.IP "--get-user"
Output only the user part.
.IP "--get-zoneid"
Output only the zoneid part.
.SH "MODIFIERS"
.IP "--urldecode"
By default each component is output using the format of the input (URL
encoded). This option makes urler instead provide it URL decoded. Note that
%20 will then output space and %09 a tab etc.
.SH WWW
https://github.com/curl/urler
