name: build

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    
    env:
      TRURL_JSON_IN: true

    strategy:
      matrix:
        build:
          - name: default
            install_packages: valgrind
            test: test-memory
          - name: clang sanitizers
            install_packages: clang
            test: test
            make_opts: >
              CC=clang
              CFLAGS="-fsanitize=address,undefined,signed-integer-overflow -Wformat -Werror=format-security -Werror=array-bounds -g"
              LDFLAGS="-fsanitize=address,undefined,signed-integer-overflow -g"

    steps:
      - uses: actions/checkout@v4

      - name: install libcurl
        run: |
          sudo apt-get update
          sudo apt-get install libcurl4-openssl-dev libjson-c-dev ${{ matrix.build.install_packages }}

      - name: code style check
        run: make checksrc

      - name: make
        run: make ${{ matrix.build.make_opts }}

      - name: sanity test
        run: ./trurl -v

      - name: test
        run: make ${{matrix.build.test}}

  cygwin:
    runs-on: windows-latest

    env:
      TRURL_JSON_IN: true

    steps:
      - uses: actions/checkout@v4

      - name: install cygwin
        uses: cygwin/cygwin-install-action@master
        with:
          packages: curl, libcurl-devel, libcurl4, make, gcc-core, python39,  libjson-c-devel

      - name: make
        run: make

      - name: sanity test
        run: ./trurl -v

      - name: test
        run: make test

  macos:
    runs-on: macos-latest

    env:
      TRURL_JSON_IN: true

    steps:
      - uses: actions/checkout@v4

      - name: Install Homebrew
        id: install-homebrew
        uses: Homebrew/actions/setup-homebrew@master
      
      - name: Install json-c
        run: brew install json-c

      - name: make
        run: make CFLAGS="-I /opt/homebrew/include" LDFLAGS="-L/opt/homebrew/lib"

      - name: sanity test
        run: ./trurl -v

      - name: test
        run: make test
